export const GET_CITY = 'GET_CITY';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_FAILURE = 'GET_CITY_FAILURE';
export const DELETE_CITY = 'DELETE_CITY';
export const CHANGE_CITIES_ORDER = 'CHANGE_CITIES_ORDER';
